### ISSUE TITLE
linter-message hidden

### ISSUE THREAD

**Issue by ricardofbarros** [AtomLinter/atom-linter#112]
Hello, maybe this a non-issue but I really couldn't find anything on the settings.

Right now it's only showing the error/warning message on the error panel when only I have my cursor at the line. 

Is this the normal behaviour? or is there some setting where I can set to see all the error/warning message that I currently I have on the file?

**Comment by Arcanemagus** [comment]
Do you have the scope set to Line instead of File?

And this repository is a helper module, I think you were looking for [this one](https://github.com/atom-community/linter/).

**Comment by ricardofbarros** [comment]
Yes you're right, I'm looking for that one, but answering your question, no I have the scope to Project so it should work, strange..
