### ISSUE TITLE
`process.execPath` returns the `atom.exe` path instead of `node.exe` path on windows

### ISSUE THREAD

**Issue by leftstick** [AtomLinter/atom-linter#14]
While upgrade [linter-jshint](https://atom.io/packages/linter-jshint) to the latest version `1.1.2`, i found it doesn't work any more on windows. See following snapshot:

![example](https://cloud.githubusercontent.com/assets/1059956/8794914/adecfd00-2fba-11e5-932c-c990f1d1e30a.png)

But the issue has nothing to do with `OSX`. I am running my `atom` on `windows`.

After some debug work, the issue is caused by `lib/helpers.coffee` line 18:

```
return @_exec(process.execPath, args, options, true)
```

The `process.execPath` returns `C:\Users\howard\AppData\Local\atom\app-1.0.2\atom.exe` which is absolutely incorrect.

**Comment by steelbrain** [comment]
That's actually by design :)
We have single binary, and pass `ATOM_SHELL_INTERNAL_USE_AS_NODE` or a similar env to make it act like node.

**Comment by leftstick** [comment]
I don't understand, do i need some extra configuration on windows? Since it doesn't work right now

**Comment by steelbrain** [comment]
No You don't :) it's by design and works perfectly that way.

**Comment by leftstick** [comment]
Actually not, the `linter` functionality doesn't work at all, the error dialog placed on top right corner whenever i change my code.

Is that means something wrong with my evn?

**Comment by steelbrain** [comment]
Yes, It's actually a bug when we pass whole of the env object instead of some selected ones, we are discussing an appropriate solution for it at the moment, You can find the workaround in the jshint issue.

**Comment by leftstick** [comment]
Thanks for quick reply, and explanation. ^_^
