### ISSUE TITLE
Small UI glitch

### ISSUE THREAD

**Issue by Stanzilla** [AtomLinter/atom-linter#26]
Steps to repro:

Open a file
Open the settings
Close Atom
Open Atom

In the lower right corner the following UI element shows up, I'm not sure what it is. It only happens when Atom restores the previous session and was focussed on the settings.

![2015-07-25_05-26-02](https://cloud.githubusercontent.com/assets/75278/8887695/b3a3e1de-328d-11e5-999b-ebcae648b7a0.png)

Disabling Linter and/or tabbing away from the settings once and then back fixes it.

**Comment by steelbrain** [comment]
I am not sure if that error's appropriate here, this repo is actually the helper module for linter providers, the main repo has moved to `atom-community` org.

**Comment by Stanzilla** [comment]
Oh, thanks. https://github.com/atom-community/linter/issues/786
