### ISSUE TITLE
CWD option not working properly

### ISSUE THREAD

**Issue by steelbrain** [AtomLinter/atom-linter#28]
Not yet confirmed, Source: https://github.com/AtomLinter/linter-javac/pull/23#issuecomment-126937495
Kelper indicated he wanted to work on this, not quite sure.
/cc @k2b6s9j

**Comment by k2b6s9j** [comment]
I'm really just planning on creating some regression tests for the
different options. Then we can see what's working and what's not.

Especially since it appears the child_process should be getting options, if
the regression tests fail then we know they aren't being passed correctly.

**Comment by daw42** [comment]
Looks like `options` is not getting passed to the `BufferedProcess` instance:

https://github.com/AtomLinter/atom-linter/blob/master/lib/helpers.coffee#L40

**Comment by k2b6s9j** [comment]
@daw42 You appear to be correct. I'm sure this is just a simple mistake which occurred from the transition from child_process to BufferedProcess.

Why again did we transition to BufferedProcess?

**Comment by steelbrain** [comment]
@k2b6s9j because it contains the `process.env` fix for windows and linux, and because it shows a nicer error if executable wasn't found and because `child_process.fork` doesn't work in node and it handles that by passing custom envs.

**Comment by k2b6s9j** [comment]
Ah. Okay.
