### ISSUE TITLE
atom-linter not found

### ISSUE THREAD

**Issue by AbdealiJK** [AtomLinter/atom-linter#34]
I am trying to make a linter using `atom-linter` like the `linter-pep8` - https://atom.io/packages/linter-pep8

The linter is for coala - https://github.com/coala-analyzer/coala
You can find the code here - https://github.com/coala-analyzer/coala-atom

I get the error mentioned below - which states the `atom-linter` library is not found. It works fine in `linter-pep8` because that plugin works for me - but the `coala-atom` plugin does not.

-----------------

**Atom Version**: 1.0.2
**System**: "Arch Linux"
**Thrown From**: [coala-atom](https://github.com/coala-analyzer/coala-atom) package, v0.0.1

### Stack Trace

Failed to activate the coala-atom package

```
At Cannot find module 'atom-linter'

Error: Cannot find module 'atom-linter'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.module.exports.provideLinter (/mnt/data/software/arch/jhbuild/other/coala-atom/lib/main.coffee:14:17)
    at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app.asar/src/package.js:369:69)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:243:16)
    at /usr/share/atom/resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-pylint",
      "linter-pylint",
      "atom-zeal"
    ]
  },
  "coala-atom": {}
}
```

### Installed Packages

```coffee
# User
coala-atom, v0.0.1
linter, v1.3.2
linter-pep8, v1.0.1

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Make sure to run `npm install atom-linter` in it's root directory :)

**Comment by AbdealiJK** [comment]
Thanks for the real quick reply :)

I copied my plugin into `~/.atom/packages` - shouldnt it be looking in atom .apm automatically ?
But installing with `npm` does work :) Thanks

**Comment by Arcanemagus** [comment]
Atom expects plugins in that directory to have been installed by apm, and thus already have all their dependencies installed. If you are developing you need to install them manually. Typing `apm install` while in the plugin folder will automatically install the dependencies just like Atom will for your users, so you should make sure to test that at least once to ensure things are working properly.

Also update your dependency version, there isn't really a reason to be developing against v1.x of this plugin :wink:.

**Comment by AbdealiJK** [comment]
Ouh - i copies it from pep :) I'll change it thanks 

Thanks for the explanation too !
