### ISSUE TITLE
Running linter in a different directory

### ISSUE THREAD

**Issue by AbdealiJK** [AtomLinter/atom-linter#35]
I want to give a command line argument `--find-config` which will find the given document from the current directory.

How do I change the directory where `atom-linter`'s `exec` function is run

**Comment by steelbrain** [comment]
Use `{cwd: '/path/to/dir'}` as option.

**Comment by AbdealiJK** [comment]
I ran it using 

```
filePath = textEditor.getPath()
console.log path.dirname(filePath)
return helpers.exec(atom.config.get('coala-atom.executable'),
                            parameters,
                            {cwd: path.dirname(filePath)})
                      .then (result) ->
          console.log "cwd - ", process.cwd()
```

the output is 
```
/home/ajk/Desktop
cwd -  /home/ajk
```

... so, it doesnt seem to be changing the directory

**Comment by steelbrain** [comment]
`process.cwd()` will always point to the current process, not the spawned one :laughing: 
We have a test where we test this CWD and it's passing btw.
