### ISSUE TITLE
The linter icon looks angry in Atom

### ISSUE THREAD

**Issue by doginthehat** [AtomLinter/atom-linter#43]
I can't unsee it.

At the scale Atom renders it, it looks like an angry face.

![screen shot 2015-08-24 at 11 53 31](https://cloud.githubusercontent.com/assets/843366/9431547/d9a67582-4a56-11e5-8280-f95ead720d06.png)

Reminds me of Cartman's angry face

![cartman](https://cloud.githubusercontent.com/assets/843366/9431549/e828586e-4a56-11e5-9993-7dc9ce1ebaa5.jpeg)

To be filed under *enhancement*.

p.s. thank you for your linter packages, they're awesome.

**Comment by steelbrain** [comment]
Any ideas of how it's icon should look like? We are always open to suggestions?

**Comment by doginthehat** [comment]
Good question..

I guess the current version's text element aren't readable so maybe text seems a bit pointless. 

Curly brackets with a tick mark? – I am clearly not a designer :neutral_face: 

Though curly brackets might offend people whose language doesn't have curly brackets – not sure if you  have a linter-ada package..

**Comment by steelbrain** [comment]
We needs ideas people
@AtomLinter/linter 
@AtomLinter/owners

**Comment by k2b6s9j** [comment]
I'm a Ruby/Crystal/CoffeeLint fan and am offended by the suggestion of a
curly brace logo! /s

In all seriousness I have been thinking about a new Linter logo. Might
throw up a sketch from my tablet later if I have anything good in mind.

**Comment by AsaAyers** [comment]
:shirt:

**Comment by doginthehat** [comment]
@AsaAyers  Are you saying a well ironed shirt = quality code ?
– That may explain some issues with my own code.

**Comment by AsaAyers** [comment]
from https://github.com/atom/atom/blob/master/CONTRIBUTING.md#git-commit-messages 

> Consider starting the commit message with an applicable emoji:
> * ￼ :shirt: `:shirt:` when removing linter warnings

I think some kind of icon based on a shirt would be clever.

**Comment by doginthehat** [comment]
@AsaAyers Ah, I see.. now that was clever... clearly too clever for some :grimacing:

**Comment by k2b6s9j** [comment]
Maybe use the Emoji One shirt as a base?

**Comment by steelbrain** [comment]
@k2b6s9j any updates?

**Comment by k2b6s9j** [comment]
Please continue this conversation at AtomLinter/atomlinter.github.io#11 where I am building the actual asset, where it can then be used elsewhere.
