### ISSUE TITLE
Linter custom elements breaks editor styling

### ISSUE THREAD

**Issue by nylki** [AtomLinter/atom-linter#48]
I am pretty sure, after updating one of the linters or the main linter package today, this happened:
![bildschirmfoto von 2015-10-02 01-07-59](https://cloud.githubusercontent.com/assets/1710598/10236113/8d498ffc-68a2-11e5-9add-a2e1c30e5916.png)
When disabling atom-linter, the problem is gone.

I am using the pen-paper-coffee syntax theme (i am the maintainer), which adds a 'margin-right` to the `.gutter` for better readability. Setting other themes, the linter custom element looks ok.

What can we do about it?

**Comment by Arcanemagus** [comment]
You would want to file this on the main [`linter`](https://github.com/atom-community/linter) package, this is a (confusingly named) helper module that provides functions many of the `linter-*` packages would need to re-implement themselves.

**Comment by Arcanemagus** [comment]
For your reference, this was implemented in https://github.com/atom-community/linter/pull/901.

**Comment by nylki** [comment]
Sorry about that! and thanks for the quick hint :)
