### ISSUE TITLE
Should colEnd do baseReduction?

### ISSUE THREAD

**Issue by xpol** [AtomLinter/atom-linter#5]
Currently we have colEnd - baseReduction:

[at line 79] (/AtomLinter/atom-linter/blob/master/lib/helpers.coffee#L79)
```coffeescript
colEnd = match.colEnd - options.baseReduction if match.colEnd
```

But consider the follow:

Assume we have a token `f` at line 1, column 2 cause an error. As a linter would reoport  error like:

   line 1 started at column 2 ended ad column 2 token f makes an error....

So should we say `ended ad column 2` or `ended ad column 3`? IMHO, we should say `ended ad column 2`.

For a linter tool the column range is inclusive (like `[x..y]`). But for atom-linter used the range is left inclusive right exclusive (like `[x..y)`).

So I think:

* we should not do `colEnd - baseReduction` for colEnd case. 
* or we should have one more option like `colEndReduction`.

**Comment by AsaAyers** [comment]
> line 1 started at column 2 ended ad column 2 token f makes an error....

This is a mistake in the linter providing the message. if it's 1 character wide the end column must be 3. Atom uses 0-based lines and columns, so when a linter returns the lint/column that a person would read, we need to reduce them by 1 to generate the address Atom needs to mark the error.

Please let me know if I'm missing something.
