### ISSUE TITLE
TextEditor constructor deprecation?

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/atom-linter#54]
Is this actually this package, or something internal to Atom?

![image](https://cloud.githubusercontent.com/assets/427137/11189977/1bbd2c6c-8c48-11e5-8e6d-c4a4dc581bb5.png)

**Comment by steelbrain** [comment]
A fix is up in #54

**Comment by steelbrain** [comment]
The fix is in `v3.3.3`

**Comment by Arcanemagus** [comment]
Thanks! Now to go update my dependency versions :wink:.
