### ISSUE TITLE
Use consistent-env package

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/atom-linter#62]
As [pointed out](https://github.com/atom/ci/pull/22#issuecomment-158514702) by @joefitzgerald there is a package avialable that provides a unified environment on OS X that matches what you would expect from `process.env` on other platforms. Since most packages use this to run their linters we should probably implement this here to simplify things for the OS X users.

Thoughts?

**Comment by steelbrain** [comment]
Asked him in #packages of slack, see https://atomio.slack.com/archives/packages/p1448052728000048

**Comment by Arcanemagus** [comment]
Bringing that conversation over here, since there is a limit to that history:

@steelbrain:

>Ping @joefitzgerald
>​[12:52] I am interested in using your environment package in linter providers, but I have a question
>​[12:53] For almost all the linter providers, the module that actually spawns the process is `atom-linter`, it's an npm module that these apm modules depend on. The fact that you are exporting a service instead of setting a global limits it's usage in `atom-linter`, to use that all the apm packages need to consume that service and then pass it on to `atom-linter::exec`, it could've been simplified if you were, say setting a global, it would be accessible everywhere and would simplify the implementation

@joefitzgerald:
>maybe you should use an executor service
>​[1:22] that depends on environment

**Comment by steelbrain** [comment]
@Arcanemagus Thank you for bringing this up, I had almost forgotten about it :)

@joefitzgerald I would love to create a service for that, but we would then have to publish this package on apm instead of npm and all packages would have to use it via `atom-package-deps` instead of directly. Also it goes against the concept of `packages` IMO, 'cause the user will see it in their list and will be given options to uninstall it

**Comment by Arcanemagus** [comment]
@steelbrain this package has been proposed to fix this issue in a few of the linter-* packages by @lexicalunit: https://www.npmjs.com/package/fix-path

Maybe we could use it if we can't work around the service requirement?

**Comment by steelbrain** [comment]
I am very much in favor of that module you linked to, but the fact that it alters a global when it could return a value would mean that when it's used by multiple packages, it would add duplicate entries. Other than that, it's using hard-coded values opposed to @joefitzgerald's package that finds out the paths by actually executing it, which is a better way IMO

**Comment by Arcanemagus** [comment]
As discussed over in https://github.com/AtomLinter/linter-shellcheck/pull/35, this really is something that should be fixed Atom side in the end, although we should probably work around this shortcoming temporarily till it lands on stable. It looks like the issue to follow for getting this into Atom: https://github.com/atom/atom/issues/4126

**Comment by steelbrain** [comment]
I've created a new [consistent-env](https://github.com/steelbrain/consistent-env) package that should make things easier for us, it's results are isolated and it's an npm package. It also has internal caching as opposed to `fix-path` by sindre. Thanks for the idea @lexicalunit
