### ISSUE TITLE
Importing failing since v3.4.0

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/atom-linter#71]
Several plugins are having issues importing this using this form:
```javascript
import helper from 'atom-linter';
```
While this works just fine:
```javascript
import * as helper from 'atom-linter';
```

Either of them _should work, but the first one seems to be broken since v3.4.0, leading to `helper` being undefined.

**Comment by steelbrain** [comment]
@Arcanemagus That's because we are now using babel and babel exports properly and recognizes own exports well. We could work-around it for backward compatibility with a `export default` though

**Comment by SpainTrain** [comment]
That would have been fine if it were behind a major version bump. Suggest we export default in 3.x and deprecate, then remove in 4.0

**Comment by steelbrain** [comment]
I am going to use commonjs modules for now, push a release, revert that change and push a major release
