### ISSUE TITLE
use `npm version` for publishing

### ISSUE THREAD

**Issue by SpainTrain** [AtomLinter/atom-linter#77]
Use `npm version <bump type>` for releases so that a git tag is created.

https://docs.npmjs.com/cli/version

**Comment by SpainTrain** [comment]
EDIT: `version` is command name

**Comment by Arcanemagus** [comment]
Tagged all previous releases that I could get a commit for.

**Comment by SpainTrain** [comment]
:heart:

**Comment by steelbrain** [comment]
Closing as I've created an even better way that uses `npm version $RELEASE_TYPE`. I've published it as [`publish`](https://github.com/steelbrain/publish). It's syntax is `publish apm|npm major|minor|patch`.

It tags the version, publishes and pushes to the repo along with the tag
