### ISSUE TITLE
Add the option to limit process execution time

### ISSUE THREAD

**Issue by stnvh** [AtomLinter/atom-linter#81]
Currently, spawned processes will tail on and eat up CPU usage (in some cases, e.g linter-phpcs). Results should be pretty much instant anyway, so I thought opening up the option to limit execution time to linters would prevent this problem.

It didn't make sense to open this on the linter-phpcs as this could happen to any linter, should the process not exit correctly.

**Comment by Arcanemagus** [comment]
Excellent idea of implementing it here, there are several linters that could benefit from this.

Other process management options that would be nice:
* `onlyOne`: Allow only one instance (but don't limit execution time unless also defined)
* `replaceCurrent`: Modifier to the above where new instances would replace the current

**Comment by braco** [comment]
Maybe this?:

* `maxRetries`: Number of times to retry execution before throwing error

**Comment by Arcanemagus** [comment]
@braco errors when attempting to execute should _always_ be thrown, the issue here is linters taking too long to execute and either slowing things down, stomping on each other, or becoming orphaned and never closing.

**Comment by steelbrain** [comment]
I'll work on this later tonight and will carve out an API for these use cases

**Comment by stnvh** [comment]
Just thinking, it would make more sense for this to be enabled by default, and have the maintainers opt-out should they need extended execution time/multiprocess/etc., which would be an edge case (I can't think of a valid use case where lengthy execution time would be needed?).

As this is a recurring problem across multiple linters (which ultimately rely on this package to handle execution), to me this seems more a bug fix than a feature request!

**Comment by willotter** [comment]
@steelbrain Any progress been made with this? Anything I can do to help?

**Comment by steelbrain** [comment]
Sorry for not addressing this sooner, gonna open a PR soon

**Comment by steelbrain** [comment]
Fix is in https://github.com/AtomLinter/atom-linter/pull/121
