### ISSUE TITLE
process.env alteration?

### ISSUE THREAD

**Issue by steak3** [AtomLinter/atom-linter#94]
Hello,

I'm investigating why I have this error when I try to perform a child_process.exec with linters activated, here:
https://github.com/AtomLinter/linter-jshint/issues/191

I made a diff of process.env in Atom, before and after linters activation, and this one seems very suspicious:
![image](https://cloud.githubusercontent.com/assets/14215758/12234377/e1c974a6-b86c-11e5-9d2b-3194c7b53eba.png)

So the OS is deleted somewhere. I just fast-explored the commits and maybe this one is related because there is some env management modification:
https://github.com/AtomLinter/atom-linter/commit/42b68ca1a784a249bcf84701e845ff60ecec0388

What do you think? Is that normal?

Thanks!

**Comment by steak3** [comment]
Also, in other conditions (when I click on a file in the tree) I have this strange difference (but it might not be related):
![image](https://cloud.githubusercontent.com/assets/14215758/12234560/27f478e4-b86e-11e5-9cd3-b9a789ca2c57.png)

**Comment by steelbrain** [comment]
Good find, fixing now

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/atom-linter/pull/95

**Comment by Arcanemagus** [comment]
A fix is published in v4.3.2 of this package, you should be able to run `apm install` from inside the linter-jshint folder to install the new dependency version. You might need to check Atom's developer tools to make sure it is loading `atom-linter` from the linter-jshint folder, if it is loading it from another folder you would need to update the dependency there as well.
